/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.Date;
import restcliente.RestClient;

/**
 *
 * @author HP
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private RestClient cliente;
    static String username;
    static String token;
    static String rol;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(String username,String token) {
        cliente = new RestClient();
        this.username = username;
        this.token = token;
        this.rol = cliente.roles(username, token).getTipo();
        System.out.println(this.rol);
        initComponents();
        System.out.println(this.username);
        botonesRoles();
    }
    
    public void botonesRoles(){
        if(rol.equals("editor")){
            this.crearEvento.setEnabled(true);
            this.crearArticulo.setEnabled(false);
            this.enviarArticulo.setEnabled(false);
            this.calificarArticulo.setEnabled(false);
        }
        if(rol.equals("autor")){
            this.crearEvento.setEnabled(false);
            this.crearArticulo.setEnabled(true);
            this.enviarArticulo.setEnabled(true);
            this.calificarArticulo.setEnabled(false);
            this.asignarRevisor.setEnabled(false);
        }
        
        if(rol.equals("revisor")){
            this.crearEvento.setEnabled(false);
            this.crearArticulo.setEnabled(false);
            this.enviarArticulo.setEnabled(false);
            this.calificarArticulo.setEnabled(true);
            this.asignarRevisor.setEnabled(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        crearEvento = new javax.swing.JButton();
        crearArticulo = new javax.swing.JButton();
        enviarArticulo = new javax.swing.JButton();
        asignarRevisor = new javax.swing.JButton();
        calificarArticulo = new javax.swing.JButton();
        informacionEventos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menú Principal");

        crearEvento.setText("Crear evento");
        crearEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearEventoActionPerformed(evt);
            }
        });

        crearArticulo.setText("Crear articulo");
        crearArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearArticuloActionPerformed(evt);
            }
        });

        enviarArticulo.setText("Enviar articulo");
        enviarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarArticuloActionPerformed(evt);
            }
        });

        asignarRevisor.setText("Asignar revisor");
        asignarRevisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarRevisorActionPerformed(evt);
            }
        });

        calificarArticulo.setText("Calificar articulo");
        calificarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calificarArticuloActionPerformed(evt);
            }
        });

        informacionEventos.setText("Informacion de eventos");
        informacionEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informacionEventosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(495, 495, 495)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calificarArticulo)
                            .addComponent(enviarArticulo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(asignarRevisor)
                            .addComponent(crearArticulo)
                            .addComponent(crearEvento))))
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(informacionEventos)
                        .addGap(249, 249, 249))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(315, 315, 315))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(crearEvento)
                .addGap(29, 29, 29)
                .addComponent(enviarArticulo)
                .addGap(18, 18, 18)
                .addComponent(crearArticulo)
                .addGap(29, 29, 29)
                .addComponent(calificarArticulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(asignarRevisor)
                .addGap(67, 67, 67)
                .addComponent(informacionEventos)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearEventoActionPerformed
        new CrearEvento(username, token).setVisible(true);
    }//GEN-LAST:event_crearEventoActionPerformed

    private void enviarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarArticuloActionPerformed
        new  EnviarArticulo(token).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_enviarArticuloActionPerformed

    private void crearArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearArticuloActionPerformed
        new CrearArticulo(token).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_crearArticuloActionPerformed

    private void asignarRevisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarRevisorActionPerformed
        new AsignarRevisor(token).setVisible(true);
    }//GEN-LAST:event_asignarRevisorActionPerformed

    private void calificarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calificarArticuloActionPerformed
        new CalificarArticulo(token).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_calificarArticuloActionPerformed

    private void informacionEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informacionEventosActionPerformed
new Informacion(token).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_informacionEventosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal(username,token).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asignarRevisor;
    private javax.swing.JButton calificarArticulo;
    private javax.swing.JButton crearArticulo;
    private javax.swing.JButton crearEvento;
    private javax.swing.JButton enviarArticulo;
    private javax.swing.JButton informacionEventos;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
