/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javearticuloscliente;

import Utils.Archivo;
import java.awt.Desktop;
import java.io.File;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import submision.ApiSubmision;
import submision.ApiSubmisionService;
import submision.Revision;
import submision.Submision;

/**
 *
 * @author USER
 */
public class MenuRevisor extends javax.swing.JFrame {

    static int usu;
    DefaultTableModel modelSubmision;
    ApiSubmision apiS;
    ApiSubmisionService servicioS;
    /**
     * Creates new form MenuRevisor
     */
    public MenuRevisor(int usu) {
        this.usu = usu;
        initComponents();
        this.setLocationRelativeTo(null);
        modelSubmision = new DefaultTableModel();
        modelSubmision.addColumn("ID revision");
        modelSubmision.addColumn("ID submision");
        modelSubmision.addColumn("ID autor");
        modelSubmision.addColumn("Autor");
        modelSubmision.addColumn("ID evento");
        modelSubmision.addColumn("Tema evento");
        modelSubmision.addColumn("Lugar evento");
        modelSubmision.addColumn("Fecha inicio evento");
        modelSubmision.addColumn("Estado");
        modelSubmision.addColumn("Calificacion");
        modelSubmision.addColumn("Archivo");
        this.jTable1.setModel(modelSubmision);
        servicioS = new ApiSubmisionService();
        apiS = servicioS.getApiSubmisionPort();
        cargarSubmisions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Javearticulos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Menú Revisor");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Mis revisiones");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Calificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ver archivo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addGap(24, 24, 24))))
            .addGroup(layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(52, 52, 52)))
                .addGap(0, 334, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        if(jTable1.getSelectedRow() == -1){
            Utils.Util.mostrarMensaje("Seleccione una revision");
        }else{
            new CalificarSubmision(usu,modelSubmision.getValueAt(jTable1.getSelectedRow(), 0).toString()).setVisible(true);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         if(jTable1.getSelectedRow() == -1){
            Utils.Util.mostrarMensaje("Seleccione un articulo");
            return;
        }
        
        String rutaProyecto = new File (".").getAbsolutePath ();
    	rutaProyecto = rutaProyecto.substring(0, rutaProyecto.length()-1) + "files/";
        String fileName = modelSubmision.getValueAt(jTable1.getSelectedRow(), 10).toString();
        try {
            File path = new File (rutaProyecto+fileName);
            Desktop.getDesktop().open(path);
       }catch (Exception ex) {
            Archivo.download(fileName);
       }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    public void removeAllRows(DefaultTableModel dtm){
        try{
            int rowCount = dtm.getRowCount();
            for (int i = rowCount - 1; i >= 0; i--) {
                dtm.removeRow(i);
            }
        } catch (Exception e){
            
        }
    }
    
    public void cargarSubmisions(){
          
        String []datos;
        List<Revision> revisiones = apiS.revisionesRevisor(new BigDecimal(String.valueOf(usu)));
        removeAllRows(modelSubmision);
        boolean hay = false;
        for(Revision r: revisiones){
            hay = true;
            datos = new String[11];
            datos[0] = String.valueOf(r.getIdrevision());
            datos[1] = String.valueOf(r.getSubmisionIdsubmision().getIdsubmision());
            datos[2] = String.valueOf(r.getSubmisionIdsubmision().getUsuarioIdusuario().getIdusuario());
            datos[3] = String.valueOf(r.getSubmisionIdsubmision().getUsuarioIdusuario().getNombres() + " " + r.getSubmisionIdsubmision().getUsuarioIdusuario().getApellidos());
            datos[4] = String.valueOf(r.getSubmisionIdsubmision().getEventoIdevento().getIdevento());
            datos[5] = String.valueOf(r.getSubmisionIdsubmision().getEventoIdevento().getTema());
            datos[6] = String.valueOf(r.getSubmisionIdsubmision().getEventoIdevento().getLugar());
            datos[7] = String.valueOf(Utils.Util.XMLGCToString(r.getSubmisionIdsubmision().getEventoIdevento().getFechainicio()));
            datos[8] = String.valueOf(r.getSubmisionIdsubmision().getEstado());
            datos[9] = String.valueOf(r.getSubmisionIdsubmision().getCalificacion());
            datos[10] = String.valueOf(r.getSubmisionIdsubmision().getArticuloIdarticulo2().getArchivo());
            modelSubmision.addRow(datos);
        }
        if(!hay){
            Utils.Util.mostrarMensaje("No hay submisiones");
        }
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRevisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRevisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRevisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRevisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuRevisor(usu).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
